///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexPilot
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("f00b10f9-f13a-4bf6-8c54-37328f150630", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexPilotRepository repository.
        /// </summary>
        public static RanorexPilotRepository repo = RanorexPilotRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Botiweb.TxtUsuario' at 75;18.", repo.Botiweb.TxtUsuarioInfo, new RecordItemIndex(0));
            repo.Botiweb.TxtUsuario.Click("75;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'u' with focus on 'Botiweb.TxtUsuario'.", repo.Botiweb.TxtUsuarioInfo, new RecordItemIndex(1));
            repo.Botiweb.TxtUsuario.PressKeys("u");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'cp' with focus on 'Botiweb.TxtUsuario'.", repo.Botiweb.TxtUsuarioInfo, new RecordItemIndex(2));
            repo.Botiweb.TxtUsuario.PressKeys("cp");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'lv01' with focus on 'Botiweb.TxtUsuario'.", repo.Botiweb.TxtUsuarioInfo, new RecordItemIndex(3));
            repo.Botiweb.TxtUsuario.PressKeys("lv01");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Botiweb.TxtSenha' at 71;10.", repo.Botiweb.TxtSenhaInfo, new RecordItemIndex(4));
            repo.Botiweb.TxtSenha.Click("71;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'boti1234' with focus on 'Botiweb.TxtSenha'.", repo.Botiweb.TxtSenhaInfo, new RecordItemIndex(5));
            repo.Botiweb.TxtSenha.PressKeys("boti1234");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Botiweb.SpanTagOK' at 23;17.", repo.Botiweb.SpanTagOKInfo, new RecordItemIndex(6));
            repo.Botiweb.SpanTagOK.Click("23;17");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
