///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RanorexPilot
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RanorexPilotRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("d1fafe04-e015-45ac-af71-0b54eb71132b")]
    public partial class RanorexPilotRepository : RepoGenBaseFolder
    {
        static RanorexPilotRepository instance = new RanorexPilotRepository();
        RanorexPilotRepositoryFolders.BotiwebAppFolder _botiweb;

        /// <summary>
        /// Gets the singleton class instance representing the RanorexPilotRepository element repository.
        /// </summary>
        [RepositoryFolder("d1fafe04-e015-45ac-af71-0b54eb71132b")]
        public static RanorexPilotRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RanorexPilotRepository() 
            : base("RanorexPilotRepository", "/", null, 0, false, "d1fafe04-e015-45ac-af71-0b54eb71132b", ".\\RepositoryImages\\RanorexPilotRepositoryd1fafe04.rximgres")
        {
            _botiweb = new RanorexPilotRepositoryFolders.BotiwebAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d1fafe04-e015-45ac-af71-0b54eb71132b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Botiweb folder.
        /// </summary>
        [RepositoryFolder("27f90b38-240e-4a5a-8e90-bcc113578ada")]
        public virtual RanorexPilotRepositoryFolders.BotiwebAppFolder Botiweb
        {
            get { return _botiweb; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class RanorexPilotRepositoryFolders
    {
        /// <summary>
        /// The BotiwebAppFolder folder.
        /// </summary>
        [RepositoryFolder("27f90b38-240e-4a5a-8e90-bcc113578ada")]
        public partial class BotiwebAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtusuarioInfo;
            RepoItemInfo _txtsenhaInfo;
            RepoItemInfo _spantagokInfo;

            /// <summary>
            /// Creates a new Botiweb  folder.
            /// </summary>
            public BotiwebAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Botiweb", "/dom[@domain='www.botiweb.com.br']", parentFolder, 30000, null, false, "27f90b38-240e-4a5a-8e90-bcc113578ada", "")
            {
                _txtusuarioInfo = new RepoItemInfo(this, "TxtUsuario", ".//input[#'txtUsuario']", 30000, null, "5f974f35-fe36-4599-b28d-00ea88f31111");
                _txtsenhaInfo = new RepoItemInfo(this, "TxtSenha", ".//input[#'txtSenha']", 30000, null, "6d65de00-afa1-457b-a9d0-ea4960fa3701");
                _spantagokInfo = new RepoItemInfo(this, "SpanTagOK", ".//a[#'linkOk']/?/?/span[@innertext='OK']", 30000, null, "70015711-f382-440e-b5c6-facf22c3b5a2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("27f90b38-240e-4a5a-8e90-bcc113578ada")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("27f90b38-240e-4a5a-8e90-bcc113578ada")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtUsuario item.
            /// </summary>
            [RepositoryItem("5f974f35-fe36-4599-b28d-00ea88f31111")]
            public virtual Ranorex.InputTag TxtUsuario
            {
                get
                {
                    return _txtusuarioInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtUsuario item info.
            /// </summary>
            [RepositoryItemInfo("5f974f35-fe36-4599-b28d-00ea88f31111")]
            public virtual RepoItemInfo TxtUsuarioInfo
            {
                get
                {
                    return _txtusuarioInfo;
                }
            }

            /// <summary>
            /// The TxtSenha item.
            /// </summary>
            [RepositoryItem("6d65de00-afa1-457b-a9d0-ea4960fa3701")]
            public virtual Ranorex.InputTag TxtSenha
            {
                get
                {
                    return _txtsenhaInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtSenha item info.
            /// </summary>
            [RepositoryItemInfo("6d65de00-afa1-457b-a9d0-ea4960fa3701")]
            public virtual RepoItemInfo TxtSenhaInfo
            {
                get
                {
                    return _txtsenhaInfo;
                }
            }

            /// <summary>
            /// The SpanTagOK item.
            /// </summary>
            [RepositoryItem("70015711-f382-440e-b5c6-facf22c3b5a2")]
            public virtual Ranorex.SpanTag SpanTagOK
            {
                get
                {
                    return _spantagokInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagOK item info.
            /// </summary>
            [RepositoryItemInfo("70015711-f382-440e-b5c6-facf22c3b5a2")]
            public virtual RepoItemInfo SpanTagOKInfo
            {
                get
                {
                    return _spantagokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}